.MODEL SMALL
DISPLAY MACRO MSG
LEA DX, MSG
MOV AH,09
INT 21H
ENDM
.DATA
LIST DB 01H,05H,07H,08H,06H
NUMBER EQU($-LIST)
KEY DB 05H
MSG1 DB 0DH, 0AH,"ELEMENT FOUND IN THE LIST....$";
MSG2 DB 0DH, 0AH,"SEARCH FAILED !! ELEMENT NOT FOUND IN THE LIST $";
.CODE
START : MOV AX, @DATA
        MOV DS,AX
        MOV CH,NUMBER-1; HIGH VALUE...
        MOV CL,00H; LOW VALUEE...

AGAIN: MOV SI,OFFSET LIST
       XOR AX,AX
       CMP CL,CH
       JE NEXT
       JNC FAILED
NEXT: MOV AL,CL
       ADD AL,CH
       SHR AL,01H;DIVIDE BY TWO
       MOV BL,AL
       XOR AH,AH; CLEAR AH
       MOV BP,AX
       MOV AL,DS:[BP][SI]
       CMP AL,KEY; COMPARE KEY AND A[i]
       JE SUCCESS; IF EQUAL,DISPLAY SUCCESS MESSAGE
       JC INCLOW
       MOV CH,BL; IF KEY &gt;A[i] SHIFT HIGH
       DEC CH
       JMP AGAIN
INCLOW: MOV CL,BL; IF KEY&lt;a[I] SHIFT LOW
        INC CL
        JMP AGAIN
SUCCESS:MOV AL,KEY
        ADD AL,30H
        MOV DL,AL
        MOV AH,02H
        INT 21H
        DISPLAY MSG1
        JMP FINAL
FAILED: DISPLAY MSG2; JOB OVER.TERMINATE.....
FINAL:MOV AH,01H
      INT 21H
      MOV AH,4CH
      INT 21H
END START
       
